import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :supervisor_phoenix, SupervisorPhoenixWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: SupervisorPhoenix.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :supervisor_phoenix, SupervisorPhoenixWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000 || System.get_env("PORT")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IxHwJpQk34Xrq0ARjjb94F/YUSe0rfJxdX256w/PatzbKEOTQF5BwJbdvP84AWs1",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
